"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import requests

APP = ['MenuBarGmail.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': False,
    'plist': {
        'LSUIElement': True,
        'CFBundleIdentifier': 'rumps',
    },
    'iconfile': 'MenuBarGmail.icns',
    'resources': [
        'MenuBarGmailMenuBarIcon.png',
        'MenuBarGmailMenuBarIconForDark.png',
        'cacerts.txt'],
    'packages': ['rumps']
}

r = requests.get('https://pki.goog/roots.pem', allow_redirects=True)
open('cacerts.txt', 'wb').write(r.content)

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
